import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Building V8 from source',
      items: [
        'build',
        'source-code',
        'build-gn',
        'cross-compile-arm',
        'cross-compile-ios',
        'ide-setup',
        'compile-arm64',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contribute',
        'respectful-code',
        'api',
        'become-committer',
        'committer-responsibility',
        'blink-layout-tests',
        'evaluate-code-coverage',
        'release-process',
        'design-review-guidelines',
        'feature-launch-process',
        'wasm-shipping-checklist',
        'flake-bisect',
        'ports',
        'official-support',
        'merge-patch',
        'node-integration',
        'security-bugs',
        'benchmarks',
        'test',
        'triage-issues',
      ],
    },
    {
      type: 'category',
      label: 'Debugging',
      items: [
        'debug-arm',
        'cross-compile-arm',
        'gdb',
        'inspector',
        'gdb-jit',
        'memory-leaks',
        'stack-trace-api',
        'd8',
        {
          type: 'link',
          label: 'V8 Tools',
          href: 'https://v8.dev/tools',
        },
      ],
    },
    {
      type: 'category',
      label: 'Embedding V8',
      items: [
        'embed',
        'version-numbers',
        'builtin-functions',
        'i18n',
        'untrusted-code-mitigations',
      ],
    },
    {
      type: 'category',
      label: 'Under the hood',
      items: [
        'ignition',
        'turbofan',
        'torque',
        'torque-builtins',
        'csa-builtins',
        'webassembly-opcode',
        'hidden-classes',
        {
          type: 'link',
          label: 'Slack Tracking - what is it?',
          href: '/blog/slack-tracking',
        },
        'wasm-compilation-pipeline',
      ],
    },
    {
      type: 'category',
      label: 'Writing optimizable JavaScript',
      items: [
        'profile',
        'profile-chromium',
        'linux-perf',
        'trace',
        'rcs',
      ],
    },
  ],
  // But you can create a sidebar manually
  // featureSidebar: [
  //   {
  //     type: 'category',
  //     label: '特性',
  //     items: [{type: 'autogenerated', dirName: 'features'}]
  //   },
  // ],

};

export default sidebars;
